source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'MaterialUI' do
    
    pod 'NBMaterialDialogIOS',
        :git => 'https://github.com/Gerst20051/NBMaterialDialogIOS.git',
        :branch => 'swift3'

end
