# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjectMapperDemo' do
  use_frameworks!
  
  pod 'RealmSwift'
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'ObjectMapper+Realm'
    
end
